import React, { useState } from 'react'
import Head from 'next/head'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ReCAPTCHA from "react-google-recaptcha";

const Contact = () => {

  const [feed, setFeed] = useState({
    email: '',
    subject: '',
    message: ''
  })

  const [verified, setVerified] = useState(true)

  const update = async (e) => {
    const { name, value } = e.target;
    setFeed({ ...feed, [name]: value })
  }
  function onChange(value) {
    console.log("Captcha value:", value);
    setVerified(false)
  }

  return (
    <>
      <Head>
        <title>The Sharkk Co. - Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="fav.png" />
      </Head>
      <section className="bg-white dark:bg-gray-900 text-xl">
        <ToastContainer
          position="top-left"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        <div className="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
          <h2 className="mb-4 text-6xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Contact Us</h2>
          <p className="mb-8 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 text-xl sm:text-2xl">Got a technical issue? Want to send feedback about our website? Let us know.</p>
          <form action='https://formspree.io/f/mnqylkng' method='POST' className="space-y-8">
            <div>
              <label htmlFor="email" className="block mb-2 text-2xl font-medium text-gray-900 dark:text-gray-300">Your email</label>
              <input type="email" name='email' value={feed.email} onChange={update} id="email" className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-2xl rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="name@gmail.com" required />
            </div>
            <div>
              <label htmlFor="subject" className="block mb-2 text-2xl font-medium text-gray-900 dark:text-gray-300">Subject</label>
              <input type="text" name='subject' value={feed.subject} onChange={update} id="subject" className="block p-3 w-full text-2xl text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="Let us know how we can help you" required />
            </div>
            <div className="sm:col-span-2">
              <label htmlFor="message" className="block mb-2 text-2xl font-medium text-gray-900 dark:text-gray-400">Your message</label>
              <textarea id="message" name='message' value={feed.message} onChange={update} rows="6" className="block p-2.5 w-full text-2xl text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Leave a comment..." required></textarea>
            </div>
            <ReCAPTCHA
            width='fit-content'
              sitekey={process.env.GOOGLE_SITE_KEY}
              type='image'
              onChange={onChange}
            />
            <button type="submit" className="py-3 px-5 text-2xl border-2 border-white font-medium text-center text-white rounded-lg bg-primary-700 sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800 disabled:bg-slate-500" disabled={verified}>Send message</button>
          </form>
        </div>
      </section>
    </>
  )
}

export default Contact
