import React from 'react'
import Head from 'next/head'

const Contact = () => {
  return (
    <>
      <Head>
        <title>The Sharkk Co. - Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="fav.png" />
      </Head>
      <div>Contact</div>
    </>
  )
}

export default Contact
