import Head from 'next/head'
import React from 'react'

const privacypolicy = () => {
    return (
        <>
            <Head>
                <title>The Sharkk Co. - Privacy Policy</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="fav.png" />
            </Head>
            <div className="container">
                <p className='italic text-5xl font-semibold mb-8'>Privacy Policy</p>
                <p>This privacy policy (“Policy”) sets out how The Sharkk Co. Pvt. Ltd. (“The Sharkk Co.”, also identified by “we” or “us” or “our” ) uses and protects any information that you give us when you use this website (individually and collectively, “Platform” ).
                    <br />
                    The Sharkk Co. is committed to ensuring that your privacy is protected. Should we ask you to provide any information by which you can be identified when using this Platform, be rest assured that it will only be used strictly in accordance with this Policy.
                    <br />
                    Please note that our Policy is subject to change at any time, and we may not be able to provide you prior notice. To ensure you are up to date with the Policy, please review this page periodically. This Policy applies to current and former visitors and customers of our Platform. By visiting and/or using our Platform, you are accepting and consenting to the practices described in this Policy.</p>
                <p className='mt-2 mb-80'><span className='inline-block px-2 -skew-x-6 bg-gray-300 font-semibold'>Note</span> - This is just a demo Next JS project.</p>

            </div>
        </>

    )
}

export default privacypolicy
