import Head from 'next/head'
import React from 'react'

const returnpolicy = () => {
    return (
        <>
            <Head>
                <title>The Sharkk Co. - Return Policy</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="fav.png" />
            </Head>
            <div className="container">
                <p className='italic text-5xl font-semibold mb-8'>Return Policy</p>
                <p className='mt-2'><span className='inline-block px-2 -skew-x-6 bg-gray-300 font-semibold'>Return Policy</span> - Over 1 Lakh+ Happy Customers</p>
                <p className='mt-2'><span className='inline-block px-2 -skew-x-6 bg-gray-300 font-semibold'>Return Period</span> - Customer can easily book the return within 7 days after delivery.</p>

                <p className='mt-2'><span className='inline-block px-2 -skew-x-6 bg-gray-300 font-semibold'>How To Book Return</span> - Customer can book the return by contacting our helpdesk.</p>

                <p className='mt-2'><span className='inline-block px-2 -skew-x-6 bg-gray-300 font-semibold'>Note 1</span> - Refunds will be transferred within 10-15 days after the reverse pickup is done.</p>

                <p className='mt-2 mb-80'> <span className='inline-block px-2 -skew-x-6 bg-gray-300 font-semibold'>NOTE 2</span> - Rs.100 will be charged as freight charges for the reverse shipment. This will be deducted from the refund amount.</p>
            </div>
        </>
    )
}

export default returnpolicy
