import Head from 'next/head'
import React from 'react'

const sources = () => {
    return (
        <>
            <Head>
                <title>The Sharkk Co. - Sources</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="fav.png" />
            </Head>
            <div className="container">
                <p className='italic text-5xl font-semibold mb-8'> Sources </p>
                <ol className='list-disc mb-96'>
                    <li className='italic'> I would like to give special thanks to mentor Harry from CodeWithHarry for guiding me in this special project. </li>
                    <li className='italic'>   The Images used from the designated sources are to be thankful</li>
                    <li className='italic'> This project is not a commercial project and is just a demo project for learning purposes. Please do not hit us a copyright. Finally, I would like to thank myself fortaking time out in learning NextJS and its application. This is my first NextJS app and is a wonderful project for a Full Stack Programmer.</li>
                </ol>
           
            </div>
        </>
    )
}

export default sources
