import Head from 'next/head'
import React from 'react'

const terms = () => {
    return (
        <>
            <Head>
                <title>The Sharkk Co. - Terms & Conditions </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="fav.png" />
            </Head>
            <div className="container">
                <p className='italic text-5xl font-semibold mb-8'> Terms & Conditions </p>
               <p> The domain name <span className='inline-block px-2 -skew-x-6 bg-gray-300 font-semibold'>www.nextecomm.netlify.app</span> (“Website”) is a site operated by The Sharkk Co Pvt. Ltd., a company incorporated under laws of India with our registered office at 224 Tantia Jogani Industrial Estate, JR Boricha Marg, Lower Parel (East), Mumbai 400 011 (“Company/The Sharkk Co”).</p>

               <p> The Sharkk Co enables the world&apos;s artists to earn money from their artwork by making it immediately and easily available for sale as a variety of products - without giving up control of their rights. We understand the importance of representing one&apos;s work with quality and respect, and we also believe it is essential that all The Sharkk Co users respect copyright. Whether you’re an artist, a customer, or just casually browsing the Website, please respect the copyright of all the works you see or buy on The Sharkk Co.</p>

               <p> By using the services on the <span className='inline-block px-2 -skew-x-6 bg-gray-300 font-semibold'>www.nextecomm.netlify.app</span>, you are agreeing to the following terms of service, conditions, policies, etc. (“Terms of Service”) including those available by hyperlink, with The Sharkk Co, which may be updated by us from time to time. Please check this page regularly to take notice of any changes we may have made to the Terms of Service.</p>

               <p> We reserve the right to review and withdraw or amend the services without notice. If you do not agree with its terms, kindly do not use this Website.</p>

               <div> The Sharkk Co provides a range of services including but not limited to, enabling you to publish, sell, comment on, promote, and purchase art related products; interact with other members; and receive the benefits of The Sharkk Co&apos;s product production service including payment processing, transaction handling, product manufacturing, packaging, order fulfilment, and customer service.<p className='mt-8 mb-80'><span className='inline-block px-2 -skew-x-6 bg-gray-300 font-semibold'>Note</span> - This is just a demo Next JS project.</p></div>

            </div>
        </>
    )
}

export default terms
